services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DB_NAME: mydb
      DB_USER: user
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 5432

    restart: always

    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  pgdata:


